# Generated by Django 4.2.2 on 2023-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata_birthdate_userdata_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
