# Generated by Django 4.2.2 on 2023-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userdata_is_admin_alter_userdata_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
