# Generated by Django 4.2.2 on 2023-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'Backe-end'), ('FE', 'Front-end'), ('iOS', 'iOS'), ('Andr', 'Android')], default='BE', max_length=4),
        ),
    ]
