# Generated by Django 4.2.2 on 2023-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracking', '0003_issue_priority_issue_status_issue_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée')], max_length=6),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], max_length=11),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('IMPROVEMENT', 'Amélioration'), ('TASK', 'Tâche')], max_length=11),
        ),
    ]
