# Generated by Django 4.2.2 on 2023-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracking', '0005_alter_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='TODO', max_length=11),
        ),
    ]
