# Generated by Django 4.2.2 on 2023-08-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracking', '0006_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issueTracking.project'),
            preserve_default=False,
        ),
    ]
